//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSWCharacterCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSWCharacterCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name_id|Name ID|string
        ///icon|Icon|string
        ///
        ///baddie|Is A Baddie|bool
        ///goodie|Is A Goodie|bool
        ///bounty_hunter|Is A Bounty Hunter|bool
        ///droid|Is A Droid|bool
        ///is_a_girl|Is A Girl|bool
        ///ghost|Is A Ghost|bool
        ///untargetable|Is Untargetable|bool
        ///jedi|Is A Jedi|bool
        ///neutral|Is Neutral|bool
        ///
        ///zipup|Zipup|bool
        ///already_got_hat|Already Got Hat|bool
        ///orientate|Orientate|bool
        ///
        ///combat_roll|Can Combat Roll|bool
        ///choke|Can Force Choke|bool
        ///can_fire|Can Fire|bool
        ///can_open_doors|Can Open Doors|bool
        ///high_jump|Can High [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllProperties {
            get {
                return ResourceManager.GetString("AllProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BLANKOOOOOOOOOOOOOOOO_LSWCC_ICON_PC {
            get {
                object obj = ResourceManager.GetObject("BLANKOOOOOOOOOOOOOOOO_LSWCC_ICON_PC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///blaster
        ///baddie
        ///zipup
        ///already_got_hat
        ///combat_roll
        ///
        ///coin_value=4110
        ///
        ///variant=stormtrooper
        ///
        ///sfx_grunt=&quot;STroop_Grunt&quot;
        ///sfx_hurt=&quot;STroop_Hurt&quot;
        ///sfx_die=&quot;STroop_Death&quot;
        ///sfx_shoot=&quot;Trooper_Fire&quot;
        ///
        ///layers_special=0,2,5
        ///layers_high=0,2,5
        ///layers_medium=0,3,5
        ///layers_low=0,4,5
        ///layers_dead=0,2,5
        ///
        ///radius=0.1
        ///miny=0
        ///maxy=0.42
        ///scale=1.0
        ///acceleration=10
        ///hit_points=1
        ///
        ///tag_locator=6
        ///helmet_locator=7
        ///
        ///tiptoe_speed=0.18
        ///walk_speed=0.6
        ///run_speed=1.2
        ///backwards_factor=0.4
        ///
        ///head_locator=2
        ///head_joi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultCharacter {
            get {
                return ResourceManager.GetString("DefaultCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formal_name=Cool Trooper
        ///base_model=STORMTROOPER/STORMTROOPER.
        /// </summary>
        internal static string DefaultProperties {
            get {
                return ResourceManager.GetString("DefaultProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ring {
            get {
                object obj = ResourceManager.GetObject("ring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
